### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by farooqkz**

### CODE REVIEW

**Comment by prp-e** [comment]
Not actually what we need as a "pull request" to our projects. Closed.

**Comment by farooqkz** [comment]
@prp-e : so you even didn't review my changes?

**Comment by prp-e** [comment]
I reviewed. I think there are more important things to do with project than a README file. 
Anyway, thanks for your help to our project.

**Comment by farooqkz** [comment]
I still don't understand.
 - If you don't want PRs, so disable them.
 - Ok, you have more important things, but what does it have with my PR?It takes time for you to click on the "Merge" button?

Anyway I deleted my repo, also good luck.

**Pull request closed without merging**
